name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
  build-server:
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v2
      - name: Build server
        run: cd server && yarn build
  build-app:
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v2
      - name: Build app
        run: cd app && yarn build
