name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server
      - name: Install dependencies
        run: yarn
      - name: Build server
        run: yarn build
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd app
      - name: Install dependencies
        run: yarn
      - name: Build app
        run: yarn build
